just added emojis :D
SethK329/CatTranslator pull request #2
Opened 2024-05-29 16:15 UTC by lucho20091

Hello there, I just added the emoji faces :D 
![image](https://github.com/SethK329/CatTranslator/assets/124323772/c59d019a-a02d-4274-a1d4-2c5506213322)

2024-05-31 05:36 UTC, SethK329 requested changes
I like the idea but I think the implementation could be better. I know how I would do it but am not sure how much collaboration you wanted on this. If you want to make the changes you can, or I can just merge it if you want to just see it through and then I will change it myself. The suggestions I have are in the comments on each file. I haven't done this before so I hope it makes sense. I appreciate your time and assistance in my learning of git!

2024-05-31 05:36 UTC, SethK329 commented on index.css
I think we should avoid an absolute position for this. Its not really necessary and means that it only works on one screen size. Instead we can put it in a container with the translation and just use margin to space it in relation to that. I do feel like they should just be together in the document and that is simpler.

2024-05-31 05:36 UTC, SethK329 commented on index.html
As was mentioned for the CSS  review we should probably put the two divs in a container together and just use margin to control the spacing and not absolute positioning.

2024-05-31 05:36 UTC, SethK329 commented on index.js
This code works but I think there is a better way that will allow for easier additions in the future. Right now we are using the index of each phrase to control which emoji is displayed but I don't really want to count them if I want to keep adding things and then shuffle them into the switch statement. What if instead of an array of strings we had an array of objects with a phrase and tone key? Then we could use different keywords for the tone of the phrase and map those to the emojis in the switch statement. Everything would then be connected to the single source of data completely.

2024-06-01 21:09 UTC, lucho20091 commented
thanks so much for the feedback bro, yes Im going to look into it and try to do better :D

2024-08-17 05:31 UTC, closed without merging

2024-08-17 05:31 UTC, SethK329 commented
I like the feature idea and we can pursue it with a different approach some other time.